### ISSUE TITLE
bibliography style in the template report

### ISSUE THREAD

**Issue by NatGr** [glouppe/info8010-deep-learning#3]
in "template-report.tex", the bibliographic style is set to "hunsrt", which produces errors  in overleaf(BibTeX I couldn't open style file hunsrt.bst : \bibstyle{hunsrt : }), by googling hunsrt, I am redirected to unsrt, which works fine on overleaf.

Is it possible that there is a typo and that "\bibliographystyle{hunsrt}" should be "\bibliographystyle{unsrt}" ?

**Comment by glouppe** [comment]
Thanks! You are actually free to use any bibliography style. Nevertheless, I modified the template to use `unsrt` instead.

(PS: for `hunsrt`, you can put the following file in the directory https://github.com/glouppe/paper-avo/blob/master/tex/hunsrt.bst)
